version: '3'

services:
  vue:
    container_name: vue-dev
    build:
      context: .
      dockerfile: vue.dockerfile
    tty: true
    ports:
      - $WEB_PORT:$WEB_PORT
    volumes:
      - ./code/app:/app
